### ISSUE TITLE
how to interpret pystac oneOf validation error

### ISSUE THREAD

**Issue by rbavery** [crim-ca/mlm-extension#37]
## :question: Question

Why is validation failing for this pystac item? I did some sleuthing and it seems like the problem might with the jsonschema itself not the STAC Item.

https://www.jsonschemavalidator.net/s/NEnpmfAn

But maybe this is a separate issue and the validator on that website does not reflect the validation we do with pystac.

My other theory is that from the examples, we don't include any that include bands only as a list of strings, though we specify in the readme that this is accepted. I'm wondering if one of raster or eo extension metadata needs to be present if any bands are specified. 

here is the gist of the json I'm validating and the error.

https://gist.github.com/rbavery/7c1875b2130dc78c48489b4ba86febb1

**Comment by fmigneault** [comment]
We could remove the extra `$comment` that are considered invalid by some parsers. 
Some parsers are stricter than others.

One thing to consider is that `$comment` are sometimes allowed and sometimes not depending on context. If they are inside an JSON object definition, it is OK (extra field ignored), but if they are under `properties` of a JSON object, this can be considered invalid since a schema-type definition is expected (or minimally `{}` for 'any').

Another thing to consider is that, because the schema is describing GeoJSON-like contents, `properties` are sometimes the JSON-schema object definition, and sometimes the actual field name within the GeoJSON.

For example:

```json
{
  "$comment": "This is the JSON-object 'properties' definition.",   # OK
  "properties": {
    "$comment": "This is the STAC-Item 'properties' field.",   # NOT OK (expect schema-type)
    "properties": {
      "$comment": "This is the JSON-object 'properties' definition for the STAC Item 'properties' field.",  # OK
      "properties": {
        "$comment": "Required MLM pretraining reference.",   # NOT OK (expect schema-type)
        "mlm:pretrained": {
          "const": false
        }
      }
    }
  }
}
```
